### ISSUE TITLE
Graph Ordering is not proper.. 

### ISSUE THREAD

**Issue by santhosh34** [OWASP/pytm#41]
Region ordering is messed if we have a bi-directional flow. LR rankdir is not working as expected.
No Option for Invisible nodes.

**Comment by izar** [comment]
hello - the ordering is governed by Graphviz. We tried to make the elements so that the user has full discretion of what dot arguments to use, so they can fix any rendering issues using dot arguments. If there's a particular change to the generated dot file that you think should become a default, please suggest it. Thanks!
